version: '3.7'

x-connections: &commonConnections
    AIRFLOW__CORE__EXECUTOR: 'CeleryExecutor'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__CELERY__RESULT_BACKEND: 'db+postgresql://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__CELERY__BROKER_URL: 'redis://redis:6379/1'

x-airflow-environment: &airflowEnvironment
    PYTHONPATH: '/home/airflow/dags'
    AIRFLOW_HOME: '/home/airflow'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'TRUE'
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: '#bca0dc'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'TRUE'

x-default-user: &defaultUser
    USERNAME: 'admin'
    PASSWORD: 'admin'
    ROLE: 'Admin'
    FIRSTNAME: 'Welbert'
    LASTNAME: 'Castro'
    EMAIL: 'welberthime@hotmail.com'

services:
    postgres:
        container_name: postgres
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        ports:
            - 5432:5432

    redis:
        container_name: redis
        image: redis:6.0.9-alpine
        ports:
            - 6379:6379

    scheduler:
        container_name: scheduler
        image: apache/airflow:2.0.0-python3.8
        depends_on:
            - postgres
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
        command: >
            bash -c "
                airflow db upgrade; \
                rm /home/airflow/airflow-scheduler.*; \
                airflow scheduler;"

    webserver:
        container_name: webserver
        image: apache/airflow:2.0.0-python3.8
        depends_on:
            - postgres
            - scheduler
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
        ports:
            - 8080:8080
        command: >
            bash -c "
                airflow users create \
                    --role $${ROLE} \
                    --username $${USERNAME} \
                    --password $${PASSWORD} \
                    --firstname $${FIRSTNAME} \
                    --lastname $${LASTNAME} \
                    --email $${EMAIL};
                airflow webserver -p 8080"

    flower:
        container_name: flower
        image: apache/airflow:2.0.0-python3.8
        depends_on:
            - scheduler
            - redis
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
        ports:
            - 5555:5555
        command: >
            bash -c "
                rm /home/airflow/airflow-flower.*; \
                airflow celery flower \
                    -p 5555 \
                    -A $${USERNAME}:$${PASSWORD} \
                    -u /flower;"

    worker:
        image: apache/airflow:2.0.0-python3.8
        depends_on:
            - redis
            - scheduler
            - webserver
            - flower
        environment: *commonConnections
        command: airflow celery worker
